name: Run BDD Cucumber Tests on Windows

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  run-bdd-tests:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17" # Update to match your project needs
          distribution: "temurin"

      # Step 3: Set up Maven
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # Step 4: Run Maven Clean Install
      - name: Build Project
        run: mvn clean install
        shell: cmd

      # Step 5: Run BDD Cucumber Tests
      - name: Run Cucumber Tests
        run: mvn test
        shell: cmd
